
import { TestPath, TestStatus } from './types';

const weg1Items = [
  "Objektart: Satteldach",
  "Eine Dachfläche",
  "Google-Tool verwenden",
  "Verschattung: Ja",
  "Prüfung Schätzung Anlagengröße und Ihre PV-Anlage im Vergleich",
  "Speicherlösung berücksichtigen: Ja",
  "Objektdaten II Pflichtfelder ausfüllen -> Dachkonstruktion: Sparrendach",
  "Prüfung Anlagengröße",
  "Untere Buttons benutzt",
  "QuickCalc Durchlauf",
  "Projekt-Artikel sind ausgewählt",
  "Vorgeschlagene Module nehmen",
  "Daten aus OD werden in MFA verwendet",
  "Speicherauslegung durchführen",
  "Vorgeschlagene Wechselrichter nehmen",
  "Montagesystem auswählen",
  "Montagesystem haben Preise / nicht 0€",
  "Vorgeschlagenen EV-Charger nehmen",
  "Produkt aus WR-Zubehör bei Zusätzlichen Einzelkomponenten auswählen",
  "Warenkorb prüfen",
  "Schnellstmögliche Lieferung auswählen",
  "Lieferadresse aus Gespeicherten Adressen eintragen und Kommission eingeben",
  "Frachtkosten berechnen",
  "Zahlungsart auswählen und Verbindlich bestellen",
  "Endkundenangebot kalkulieren",
  "PDF-Ausgabe prüfen und validieren",
  "Werte in Ertragsprognose validieren",
  "Werte in Finanzierung validieren und Einmaliger Zuschuss ausfüllen",
  "Stromverbrauchsprofil bearbeiten, Wärmepumpe und Elektromobilität berücksichtigen",
  "Vergleich aktualisieren und Einstellungen übernehmen",
  "Grafiken und Darstellungen in Ergebnisübersicht Wirtschaftlichkeit überprüfen und validieren",
  "Anfrageart: Projektanfrage an EWS senden",
  "Kontaktdaten eingeben",
  "Bestellübersicht anschauen und validieren",
  "Detaillierte Projektdaten anschauen und validieren",
  "Projekt speichern",
];

const weg2Items = [
  "Objektart: Flachdach",
  "Zwei Dachflächen",
  "Daten Manuell eingeben",
  "Verschattung: Nein",
  "Prüfung Schätzung Anlagengröße und Ihre PV-Anlage im Vergleich",
  "Speicherlösung berücksichtigen: Nein",
  "DF 1 Aufständerung: Keine Aufständerung",
  "DF 1 Pflichtfelder ausfüllen",
  "DF 2 Aufständerung: Ballast-optimiert Ost-West",
  "DF 2 Pflichtfelder ausfüllen",
  "Prüfung Anlagengröße",
  "QuickCalc durchlauf",
  "Module Filtern nach Hersteller Trinasolar",
  "Module mit Anzahl von Vorgeschlagenem Modul in Warenkorb legen",
  "Modulfeldauslegung durchlaufen",
  "Ohne Speicher planen",
  "Vorgeschlagene Wechselrichter nehmen",
  "Passendes Montagesystem für beide Dachflächen auswählen",
  "Ohne EV-Charger planen",
  "Produkt aus Anlagen-Zubehör bei Zusätzlichen Einzelkomponenten auswählen",
  "Warenkorb prüfen",
  "Zum Wunschtermin auswählen und mit Datepicker Termin aussuchen",
  "Lieferadresse aus Gespeicherten Adressen eintragen und Kommission eingeben",
  "Frachtkosten berechnen",
  "Zahlungsart auswählen und Anfrage senden",
  "Endkundenangebot kalkulieren",
  "PDF-Ausgabe prüfen und validieren",
  "Werte in Ertragsprognose validieren",
  "Werte in Finanzierung validieren",
  "Eingaben in WKB ändern",
  "Grafiken und Darstellungen in Ergebnisübersicht Wirtschaftlichkeit überprüfen und validieren",
  "Anfrageart: Projekt nur Speichern",
  "Bestellübersicht anschauen und validieren",
  "Detaillierte Projektdaten anschauen und validieren",
  "Projekt speichern",
];

export const TEST_PATHS: TestPath[] = [
  {
    id: 1,
    title: 'Weg 1: Satteldach',
    items: weg1Items.map((desc, index) => ({
      id: index,
      description: desc,
      status: TestStatus.NOT_STARTED,
    })),
  },
  {
    id: 2,
    title: 'Weg 2: Flachdach',
    items: weg2Items.map((desc, index) => ({
      id: index,
      description: desc,
      status: TestStatus.NOT_STARTED,
    })),
  },
];
